name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main   # change if your default branch is master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend   # 👈 your React project folder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Copy index.html as 404.html for React Router SPA fallback
      - name: SPA fallback for GitHub Pages
        run: |
          if [ -f dist/index.html ]; then
            cp dist/index.html dist/404.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist   # 👈 Vite outputs here
          publish_branch: gh-pages
